package pl.jf.lab.db;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Persistence entity representing a complete calculation record.
 * This class maps to the CALCULATIONS table and manages the relation between
 * an operation and its associated matrices.
 *
 * @author JakubFilipiak
 * @version 2.0
 */
@Entity
@Table(name = "CALCULATIONS")
public class CalculationEntity {

    /** The unique identifier for the calculation record. Generated by the DB. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The name of the performed operation (e.g., ADD, MULTIPLY). */
    private String operationName;

    /** The exact date and time when the operation was executed. */
    private LocalDateTime timestamp;

    /** List of matrix data entries associated with this specific calculation. */
    @OneToMany(mappedBy = "calculation", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private List<MatrixDataEntity> matrices = new ArrayList<>();

    /**
     * Default constructor required by the JPA specification.
     */
    public CalculationEntity() {}

    /**
     * Constructs a new calculation record with a given operation name.
     * Initializes the timestamp to the current local time.
     *
     * @param operationName The name of the operation performed.
     */
    public CalculationEntity(String operationName) {
        this.operationName = operationName;
        this.timestamp = LocalDateTime.now();
    }

    /**
     * Adds a matrix entry to the calculation and sets up the bidirectional relationship.
     *
     * @param matrix The MatrixDataEntity object to be linked with this calculation.
     */
    public void addMatrix(MatrixDataEntity matrix) {
        matrices.add(matrix);
        matrix.setCalculation(this);
    }

    /**
     * Retrieves the database ID of this calculation.
     *
     * @return The primary key ID of the record.
     */
    public Long getId() { return id; }

    /**
     * Retrieves the operation name.
     *
     * @return String containing the operation name.
     */
    public String getOperationName() { return operationName; }

    /**
     * Retrieves the list of associated matrices.
     *
     * @return A list of {@link MatrixDataEntity} objects.
     */
    public List<MatrixDataEntity> getMatrices() { return matrices; }
    
    /**
     * Retrieves the execution timestamp.
     * * @return The {@link LocalDateTime} of the calculation.
     */
    public LocalDateTime getTimestamp() { return timestamp; }
}